In [38]:
import helper_functions as hf
import pandas as pd
import numpy as np

pd.set_option('display.float_format', '{:.5e}'.format)

In [ ]:
degree_array = [10,30,50]


In [14]:
import scipy.linalg as SLA

k_inv = SLA.inv(hf.get_matrix(10))

In [2]:
k = hf.get_matrix(10)

In [3]:
k

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
        0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667,
        0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909],
       [0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714,
        0.125     , 0.11111111, 0.1       , 0.09090909, 0.08333333],
       [0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ,
        0.11111111, 0.1       , 0.09090909, 0.08333333, 0.07692308],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
        0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
        0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667],
       [0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909,
        0.08333333, 0.07692308, 0.07142857, 0.06666667, 0.0625    ],
       [0.125     , 0.11111111, 0.1      

In [8]:
print(hf.swap_cols(k,3,5,to_row=8))

[[1.         0.5        0.33333333 0.25       0.2        0.16666667
  0.14285714 0.125      0.11111111 0.1       ]
 [0.5        0.33333333 0.25       0.2        0.16666667 0.14285714
  0.125      0.11111111 0.1        0.09090909]
 [0.33333333 0.25       0.2        0.125      0.14285714 0.16666667
  0.11111111 0.1        0.09090909 0.08333333]
 [0.25       0.2        0.16666667 0.11111111 0.125      0.14285714
  0.1        0.09090909 0.08333333 0.07692308]
 [0.2        0.16666667 0.14285714 0.1        0.11111111 0.125
  0.09090909 0.08333333 0.07692308 0.07142857]
 [0.16666667 0.14285714 0.125      0.09090909 0.1        0.11111111
  0.08333333 0.07692308 0.07142857 0.06666667]
 [0.14285714 0.125      0.11111111 0.08333333 0.09090909 0.1
  0.07692308 0.07142857 0.06666667 0.0625    ]
 [0.125      0.11111111 0.1        0.07692308 0.08333333 0.09090909
  0.07142857 0.06666667 0.0625     0.05882353]
 [0.11111111 0.1        0.09090909 0.08333333 0.07692308 0.07142857
  0.06666667 0.0625     

In [34]:
c = k[5:,5:].flatten()

In [37]:
c

array([0.11111111, 0.08333333, 0.07692308, 0.07142857, 0.06666667,
       0.1       , 0.07692308, 0.07142857, 0.06666667, 0.0625    ,
       0.09090909, 0.07142857, 0.06666667, 0.0625    , 0.05882353,
       0.07142857, 0.06666667, 0.0625    , 0.05882353, 0.05555556,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [36]:
np.flip(c)

array([0.05263158, 0.05555556, 0.05882353, 0.0625    , 0.06666667,
       0.05555556, 0.05882353, 0.0625    , 0.06666667, 0.07142857,
       0.05882353, 0.0625    , 0.06666667, 0.07142857, 0.09090909,
       0.0625    , 0.06666667, 0.07142857, 0.07692308, 0.1       ,
       0.06666667, 0.07142857, 0.07692308, 0.08333333, 0.11111111])

In [16]:
abs(k_inv).min()

99.99944937136024