In [1]:
import helper_functions as hf
import pandas as pd
import numpy as np
import math
import scipy.linalg as SLA

pd.set_option('display.float_format', '{:.5e}'.format)

In [2]:
degree_array = [10]

In [2]:
degree = 5
A, b = hf.get_matrix(degree), hf.get_array(degree)
SLA.cho_factor(A)

(array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
        [0.5       , 0.28867513, 0.28867513, 0.25980762, 0.23094011],
        [0.33333333, 0.25      , 0.0745356 , 0.1118034 , 0.12777531],
        [0.25      , 0.2       , 0.16666667, 0.01889822, 0.03779645],
        [0.2       , 0.16666667, 0.14285714, 0.125     , 0.0047619 ]]),
 False)

In [3]:
hf.CHOP(A,b)

[[1.         0.         0.         0.         0.        ]
 [0.5        0.         0.         0.         0.        ]
 [0.33333333 0.         0.         0.         0.        ]
 [0.25       0.         0.         0.         0.        ]
 [0.2        0.         0.         0.         0.        ]]
[[1.         0.         0.         0.         0.        ]
 [0.5        0.28867513 0.         0.         0.        ]
 [0.33333333 0.28867513 0.         0.         0.        ]
 [0.25       0.25980762 0.         0.         0.        ]
 [0.2        0.23094011 0.         0.         0.        ]]
[[1.         0.         0.         0.         0.        ]
 [0.5        0.28867513 0.         0.         0.        ]
 [0.33333333 0.28867513 0.0745356  0.         0.        ]
 [0.25       0.25980762 0.1118034  0.         0.        ]
 [0.2        0.23094011 0.12777531 0.         0.        ]]
[[1.         0.         0.         0.         0.        ]
 [0.5        0.28867513 0.         0.         0.        ]
 [0.3333333

d:\CMI\SEM 2 JAN-APR-23\LAA23 ~ Priyavrat Deshpande\Assignments\Solutions\LAA_grpa_5\helper_functions.py:97: RuntimeWarning: divide by zero encountered in scalar divide
  C[i] = (arr[i] - substracting_factor) / mat[i, i]
d:\CMI\SEM 2 JAN-APR-23\LAA23 ~ Priyavrat Deshpande\Assignments\Solutions\LAA_grpa_5\helper_functions.py:243: RuntimeWarning: invalid value encountered in matmul
  x = P.T@z                                   # solves for x, here, x = Q*z = trans(P)*z


{'norm': nan, 'time': 4252500.0}

In [4]:
np.dot([1,3],[3,5])

18

In [7]:
import math
e = 5
eval('math.sqrt(e)')

2.23606797749979

In [14]:
import scipy.linalg as SLA

k_inv = SLA.inv(hf.get_matrix(10))

In [2]:
k = hf.get_matrix(10)

In [3]:
k

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
        0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667,
        0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909],
       [0.33333333, 0.25      , 0.2       , 0.16666667, 0.14285714,
        0.125     , 0.11111111, 0.1       , 0.09090909, 0.08333333],
       [0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ,
        0.11111111, 0.1       , 0.09090909, 0.08333333, 0.07692308],
       [0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
        0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ,
        0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667],
       [0.14285714, 0.125     , 0.11111111, 0.1       , 0.09090909,
        0.08333333, 0.07692308, 0.07142857, 0.06666667, 0.0625    ],
       [0.125     , 0.11111111, 0.1      

In [8]:
print(hf.swap_cols(k,3,5,to_row=8))

[[1.         0.5        0.33333333 0.25       0.2        0.16666667
  0.14285714 0.125      0.11111111 0.1       ]
 [0.5        0.33333333 0.25       0.2        0.16666667 0.14285714
  0.125      0.11111111 0.1        0.09090909]
 [0.33333333 0.25       0.2        0.125      0.14285714 0.16666667
  0.11111111 0.1        0.09090909 0.08333333]
 [0.25       0.2        0.16666667 0.11111111 0.125      0.14285714
  0.1        0.09090909 0.08333333 0.07692308]
 [0.2        0.16666667 0.14285714 0.1        0.11111111 0.125
  0.09090909 0.08333333 0.07692308 0.07142857]
 [0.16666667 0.14285714 0.125      0.09090909 0.1        0.11111111
  0.08333333 0.07692308 0.07142857 0.06666667]
 [0.14285714 0.125      0.11111111 0.08333333 0.09090909 0.1
  0.07692308 0.07142857 0.06666667 0.0625    ]
 [0.125      0.11111111 0.1        0.07692308 0.08333333 0.09090909
  0.07142857 0.06666667 0.0625     0.05882353]
 [0.11111111 0.1        0.09090909 0.08333333 0.07692308 0.07142857
  0.06666667 0.0625     

In [34]:
c = k[5:,5:].flatten()

In [37]:
c

array([0.11111111, 0.08333333, 0.07692308, 0.07142857, 0.06666667,
       0.1       , 0.07692308, 0.07142857, 0.06666667, 0.0625    ,
       0.09090909, 0.07142857, 0.06666667, 0.0625    , 0.05882353,
       0.07142857, 0.06666667, 0.0625    , 0.05882353, 0.05555556,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [36]:
np.flip(c)

array([0.05263158, 0.05555556, 0.05882353, 0.0625    , 0.06666667,
       0.05555556, 0.05882353, 0.0625    , 0.06666667, 0.07142857,
       0.05882353, 0.0625    , 0.06666667, 0.07142857, 0.09090909,
       0.0625    , 0.06666667, 0.07142857, 0.07692308, 0.1       ,
       0.06666667, 0.07142857, 0.07692308, 0.08333333, 0.11111111])

In [16]:
abs(k_inv).min()

99.99944937136024